Update ci-cd-project-card-validation.yml

diff --git a/.github/workflows/ci-cd-project-card-validation.yml b/.github/workflows/ci-cd-project-card-validation.yml
--- a/.github/workflows/ci-cd-project-card-validation.yml
+++ b/.github/workflows/ci-cd-project-card-validation.yml
@@ -166,24 +166,49 @@ jobs:
           project_url: ${{ env.PROJECT_URL }}
 
       - name: Is merging allowed for this pull request?
+        id: is_merging_allowed
         if: ${{ steps.get_mergable_field_value.outputs.values != env.OPTION_MERGABLE_PR_ALLOW_MERGE }}
         run: |
           echo "This CI/CD workflow requires the pull request have the 'Mergable' setting assigned the value '${{ env.OPTION_MERGABLE_PR_ALLOW_MERGE }}' to proceed."
-          exit 1
+          echo "is_merging_allowed=true" >> $GITHUB_OUTPUT
+          # exit 1
 
       - name: Is release type set for this pull request?
+        id: is_release_type_set
         if: ${{ needs.variables.outputs.RELEASE_TYPE == '' }}
         run: |
           echo "This CI/CD workflow requires the pull request to have the 'Release Type' setting assigned in order to proceed."
-          exit 1
+          echo "is_release_type_set=true" >> $GITHUB_OUTPUT       
+          # exit 1
 
-      - name: Return workflow status
-        run: |
-          if (always() && failure()); then
+    outputs:
+      success: ${{ steps.is_merging_allowed.outputs.success && steps.is_release_type_set.outputs.success }}
+      
+      # - name: Return status
+      #   run: |
+      #     if (always() && failure()); then
+      #       echo "Project card validation FAILED."
+      #       exit 1
+      #     else
+      #       echo "Project card validation SUCCESSFUL."
+      #       exit 0          
+      #     fi
+      
+  pull_request_can_proceed_status_check:
+    # Use this job name in conjunction with branch protection requiring status checks to prevent merging
+    # see https://calmcode.io/github-actions/prevent-merge.html
+    needs: [verify_pull_request_can_proceed]
+    if: always() # always run, so we never skip the status check
+    runs-on: ubuntu-latest
+    steps:
+      # pass step only when output of previous verify_pull_request_can_proceed job is set
+      - run: |
+          passed="${{ needs.verify_pull_request_can_proceed.outputs.success }}"
+          if [[ $passed == "true" ]]; then
+            echo "Project card validation SUCCESSFUL."
+            exit 0
+          else
             echo "Project card validation FAILED."
             exit 1
-          else
-            echo "Project card validation SUCCESSFUL."
-            exit 0          
-          fi          
-      
+          fi
+    
